services:
  - type: web
    name: sudeste-rp
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sudeste-rp-db
          property: connectionString
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: DISCORD_WL_CHANNEL_ID
        sync: false
      - key: DISCORD_STAFF_ROLE_ID
        sync: false
      - key: STAFF_PANEL_PASSWORD
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false

databases:
  - name: sudeste-rp-db
    plan: free
