const http=require("http");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const nacl=require("tweetnacl");
const {Client,GatewayIntentBits}=require("discord.js");
const {Pool}=require("pg");

const PORT=Number(process.env.PORT||10000),ROOT=__dirname,DISCORD_API="https://discord.com/api/v10";
const MIME={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".ico":"image/x-icon"};
const sessions=new Set();
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5}):null;
function json(res,data,status=200,extra={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type",...extra});res.end(JSON.stringify(data))}
function clean(v,max=1500){return String(v??"").trim().slice(0,max)}
function limitDiscord(v,max=950){const t=clean(v,1500);return t.length>max?t.slice(0,max-3)+"...":t}
function readBody(req){return new Promise((resolve,reject)=>{let raw="";req.on("data",c=>{raw+=c;if(raw.length>200000)req.destroy()});req.on("end",()=>{try{resolve(JSON.parse(raw||"{}"))}catch{reject(new Error("JSON inválido"))}});req.on("error",reject)})}
function getCookie(req,name){const m=(req.headers.cookie||"").match(new RegExp(`(?:^|; )${name}=([^;]+)`));return m?decodeURIComponent(m[1]):""}
function staff(req,res){if(!sessions.has(getCookie(req,"sd_staff"))){json(res,{ok:false,error:"Não autorizado."},401);return false}return true}
async function discord(method,endpoint,body){if(!process.env.DISCORD_BOT_TOKEN)throw Error("DISCORD_BOT_TOKEN não configurado");const r=await fetch(DISCORD_API+endpoint,{method,headers:{Authorization:`Bot ${process.env.DISCORD_BOT_TOKEN}`,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw Error(`Discord HTTP ${r.status} ${text.slice(0,300)}`);try{return text?JSON.parse(text):null}catch{return null}}
async function webhookEdit(applicationId,token,body){const r=await fetch(`${DISCORD_API}/webhooks/${applicationId}/${token}/messages/@original`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw Error(`Discord webhook HTTP ${r.status} ${text.slice(0,300)}`);return text?JSON.parse(text):null}
async function initDb(){if(!pool){console.warn("DATABASE_URL não configurado — usando memória temporariamente.");return}await pool.query(`CREATE TABLE IF NOT EXISTS whitelists(id BIGSERIAL PRIMARY KEY,protocol TEXT UNIQUE NOT NULL,discord_id TEXT NOT NULL,release_id TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Em análise','Aprovada','Reprovada')),data JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),reviewed_by TEXT,review_reason TEXT,reviewed_at TIMESTAMPTZ)`);await pool.query(`CREATE INDEX IF NOT EXISTS idx_wl_discord ON whitelists(discord_id)`);await pool.query(`CREATE INDEX IF NOT EXISTS idx_wl_release ON whitelists(release_id)`);await pool.query(`CREATE UNIQUE INDEX IF NOT EXISTS uq_wl_active_discord ON whitelists(discord_id) WHERE status IN ('Em análise','Aprovada')`);await pool.query(`CREATE UNIQUE INDEX IF NOT EXISTS uq_wl_active_release ON whitelists(release_id) WHERE status IN ('Em análise','Aprovada')`);console.log("PostgreSQL conectado • armazenamento persistente ativo")}
const memory=new Map();
function rowToW(r){return r?{...r.data,protocol:r.protocol,status:r.status,created_at:new Date(r.created_at).toISOString(),updated_at:new Date(r.updated_at).toISOString(),reviewed_by:r.reviewed_by,review_reason:r.review_reason,reviewed_at:r.reviewed_at?new Date(r.reviewed_at).toISOString():null}:null}
async function createW(data){const w={...data,created_at:new Date().toISOString(),reviewed_by:null,review_reason:null,reviewed_at:null,status:"Em análise"};if(!pool){memory.set(w.protocol,w);return w}const r=await pool.query(`INSERT INTO whitelists(protocol,discord_id,release_id,status,data) VALUES($1,$2,$3,$4,$5) RETURNING *`,[w.protocol,w.discord,w.idlib,w.status,w]);return rowToW(r.rows[0])}
async function listW(status){if(!pool)return [...memory.values()].filter(w=>!status||w.status===status).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const r=status?await pool.query(`SELECT * FROM whitelists WHERE status=$1 ORDER BY created_at DESC`,[status]):await pool.query(`SELECT * FROM whitelists ORDER BY created_at DESC`);return r.rows.map(rowToW)}
async function getW(protocol){if(!pool)return memory.get(protocol)||null;const r=await pool.query(`SELECT * FROM whitelists WHERE protocol=$1 LIMIT 1`,[protocol]);return rowToW(r.rows[0])}
async function existingW(discordId,idlib){if(!pool)return [...memory.values()].find(w=>(w.discord===discordId||w.idlib===idlib)&&w.status!=="Reprovada")||null;const r=await pool.query(`SELECT * FROM whitelists WHERE (discord_id=$1 OR release_id=$2) AND status IN ('Em análise','Aprovada') ORDER BY CASE WHEN status='Aprovada' THEN 0 ELSE 1 END, created_at DESC LIMIT 1`,[discordId,idlib]);return rowToW(r.rows[0])}
async function reviewW(protocol,status,reviewedBy,reason){const w=await getW(protocol);if(!w)return null;if(w.status!=="Em análise")return w;const reviewedAt=new Date().toISOString();if(!pool){w.status=status;w.reviewed_by=reviewedBy||"Staff";w.review_reason=reason||null;w.reviewed_at=reviewedAt;memory.set(protocol,w);return w}const r=await pool.query(`UPDATE whitelists SET status=$2,reviewed_by=$3,review_reason=$4,reviewed_at=$5,updated_at=NOW(),data=jsonb_set(jsonb_set(jsonb_set(data,'{status}',to_jsonb($2::text)),'{reviewed_by}',to_jsonb($3::text)),'{review_reason}',to_jsonb($4::text)) WHERE protocol=$1 AND status='Em análise' RETURNING *`,[protocol,status,reviewedBy||"Staff",reason||null,reviewedAt]);return rowToW(r.rows[0])||await getW(protocol)}
const labels={roleplay:"📖 O que é RP",motivo:"🎯 Objetivo de bom RP",ic_ooc:"🧠 IC x OOC",personagem:"👤 Interpretação",rdm:"🔴 RDM",vdm:"🚗 VDM",mg:"🧩 Metagaming",powergaming:"⚙️ Power Gaming",combatlog:"🚪 Combat Log",copmeta:"🕵️ Cop Meta",failrp:"🎭 Fail RP",regras:"📚 Quebra de regra",denuncia:"📢 Denúncia",situacao_rendido:"⚠️ Rendição",abordagem:"🚓 Abordagem",safezone:"🛡️ Safe Zone",metagaming_situacao:"💬 Informação externa",procurado:"🔎 Procurado",queda:"🌐 Queda/Crash",conflito:"🔥 Conflito",safezone_pratica:"🏙️ Situação em Safe Zone",prioridade_staff:"⚖️ Decisão da Staff",voz:"🎙️ Discordância",compromisso:"🤝 Imersão",inatividade:"⏳ Atividade",motivo_final:"⭐ Por que aprovar",regra_ganho:"🏆 Regra x vitória"};
const fieldKeys=["roleplay","motivo","ic_ooc","personagem","rdm","vdm","mg","powergaming","combatlog","copmeta","failrp","regras","denuncia","situacao_rendido","abordagem","safezone","metagaming_situacao","procurado","queda","conflito","safezone_pratica","prioridade_staff","voz","compromisso","inatividade","motivo_final","regra_ganho"];
function embed(w,part=1){const base=[{name:"👤 Jogador",value:limitDiscord(w.nome),inline:true},{name:"🆔 ID de liberação",value:limitDiscord(w.idlib),inline:true},{name:"💬 Discord ID",value:limitDiscord(w.discord),inline:true},{name:"🎂 Idade",value:String(w.idade),inline:true},{name:"🎮 Experiência",value:limitDiscord(w.experiencia),inline:true}];const slice=part===1?fieldKeys.slice(0,10):fieldKeys.slice(10);for(const k of slice)if(w[k])base.push({name:labels[k]||k,value:limitDiscord(w[k])});return{title:part===1?"📋 NOVA WHITELIST — SUDESTE RP":"📋 WHITELIST — CONTINUAÇÃO",description:`**Protocolo:** \`${w.protocol}\`\n**Status:** **${w.status}**`,color:w.status==="Aprovada"?0x20b26b:w.status==="Reprovada"?0xc93648:0x1683ff,fields:base,footer:{text:`Sudeste RP • WL • ${w.reviewed_by?`Analisada por ${w.reviewed_by}`:"Aguardando Staff"}`}}}
function embeds(w){return [embed(w,1),embed(w,2)]}
function components(w){return w.status==="Em análise"?[{type:1,components:[{type:2,style:3,label:"Aprovar",custom_id:`wl:approve:${w.protocol}`},{type:2,style:4,label:"Reprovar",custom_id:`wl:reject:${w.protocol}`}]}]:[]}
async function postWL(w){if(!process.env.DISCORD_WL_CHANNEL_ID)throw Error("DISCORD_WL_CHANNEL_ID não configurado");return discord("POST",`/channels/${process.env.DISCORD_WL_CHANNEL_ID}/messages`,{embeds:embeds(w),components:components(w)})}
async function dm(user,w){if(!/^\d{17,20}$/.test(user))return false;try{const d=await discord("POST","/users/@me/channels",{recipient_id:user});let content;if(w.status==="Em análise")content=`📋 **Whitelist recebida — Sudeste RP**\n\nSua whitelist foi enviada com sucesso e está **em análise pela Staff**.\n\n**Protocolo:** ${w.protocol}\n\nAguarde a análise. Você receberá outra DM quando sua WL for **aprovada ou reprovada**.`;else if(w.status==="Aprovada")content=`✅ **Sua Whitelist foi APROVADA no Sudeste RP!**\n\nProtocolo: **${w.protocol}**\n\nA equipe aprovou sua entrada. Bem-vindo à cidade!`;else content=`❌ **Sua Whitelist foi REPROVADA no Sudeste RP.**\n\nProtocolo: **${w.protocol}**\nMotivo: **${clean(w.review_reason||"Não informado",500)}**\n\nLeia as diretrizes e tente novamente quando estiver disponível.`;await discord("POST",`/channels/${d.id}/messages`,{content});return true}catch(e){console.error("WL DM:",e.message);return false}}
function roleNameMatch(role,names){const n=String(role?.name||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();return names.some(x=>n===x)}
async function setMemberRoles(guildId,userId,status){if(!guildId||!userId||!process.env.DISCORD_BOT_TOKEN)return false;try{const roles=await discord("GET",`/guilds/${guildId}/roles`);const names={notVerified:["unverified","nao verificado"],pending:["em analise","analise wl","wl em analise"],verified:["verified","verificado","verificado na wl"]};const find=arr=>roles.find(r=>roleNameMatch(r,arr));const nv=find(names.notVerified),an=find(names.pending),vf=find(names.verified);const member=await discord("GET",`/guilds/${guildId}/members/${userId}`);const current=new Set(member.roles||[]),add=[],remove=[];if(status==="join"){if(nv&&!current.has(nv.id))add.push(nv.id);if(an&&current.has(an.id))remove.push(an.id);if(vf&&current.has(vf.id))remove.push(vf.id)}else if(status==="Em análise"){if(an&&!current.has(an.id))add.push(an.id);if(nv&&current.has(nv.id))remove.push(nv.id);if(vf&&current.has(vf.id))remove.push(vf.id)}else if(status==="Aprovada"){if(vf&&!current.has(vf.id))add.push(vf.id);if(nv&&current.has(nv.id))remove.push(nv.id);if(an&&current.has(an.id))remove.push(an.id)}else if(status==="Reprovada"){if(nv&&!current.has(nv.id))add.push(nv.id);if(an&&current.has(an.id))remove.push(an.id);if(vf&&current.has(vf.id))remove.push(vf.id)}for(const id of remove)await discord("DELETE",`/guilds/${guildId}/members/${userId}/roles/${id}`);for(const id of add)await discord("PUT",`/guilds/${guildId}/members/${userId}/roles/${id}`);return true}catch(e){console.error("WL CARGOS:",e.message);return false}}
async function guildForWL(){if(!process.env.DISCORD_WL_CHANNEL_ID)return null;try{const c=await discord("GET",`/channels/${process.env.DISCORD_WL_CHANNEL_ID}`);return c.guild_id||null}catch(e){console.error("WL GUILD:",e.message);return null}}
const dataKeys=["nome","idlib","discord","idade","experiencia",...fieldKeys];
async function wl(req,res){if(req.method==="OPTIONS")return json(res,{},204);if(req.method!=="POST")return json(res,{ok:false,error:"Método não permitido."},405);try{const b=await readBody(req),d={};for(const k of dataKeys)d[k]=clean(b[k],k==="nome"?80:k==="idlib"?20:k==="discord"?100:k==="idade"?3:1500);if(dataKeys.some(k=>!d[k]))return json(res,{ok:false,error:"Preencha todos os campos obrigatórios."},400);if(!/^\d+$/.test(d.idlib))return json(res,{ok:false,error:"ID de liberação inválido."},400);if(!/^\d{17,20}$/.test(d.discord))return json(res,{ok:false,error:"Informe o ID numérico do Discord (17 a 20 dígitos)."},400);const age=Number(d.idade);if(!Number.isInteger(age)||age<13||age>99)return json(res,{ok:false,error:"Idade inválida."},400);const old=await existingW(d.discord,d.idlib);if(old)return json(res,{ok:false,error:old.status==="Aprovada"?"Este Discord ou ID de liberação já possui uma WL aprovada. Você não pode enviar outra WL.":"Você já possui uma WL em análise. Aguarde a decisão da Staff."},409);const protocol=`SD-${crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase()}`;let w;try{w=await createW({...d,idade:age,protocol})}catch(e){if(String(e.message).includes("uq_wl_active")||String(e.message).includes("duplicate key"))return json(res,{ok:false,error:"Este Discord ou ID de liberação já possui uma WL ativa ou aprovada."},409);throw e}try{await postWL(w)}catch(e){if(!pool)memory.delete(protocol);else await pool.query("DELETE FROM whitelists WHERE protocol=$1",[protocol]);console.error("WL Discord:",e.message);return json(res,{ok:false,error:"Não foi possível enviar a WL para a Staff no Discord."},502)}const guildId=await guildForWL();if(guildId)await setMemberRoles(guildId,w.discord,"Em análise");await dm(w.discord,w);return json(res,{ok:true,protocol})}catch(e){console.error("WL:",e);return json(res,{ok:false,error:"Dados inválidos ou erro interno."},400)}}
async function staffApi(req,res,url){if(url.pathname==="/api/staff/login"&&req.method==="POST")return readBody(req).then(b=>{const expected=process.env.STAFF_PANEL_PASSWORD||"";if(!expected)return json(res,{ok:false,error:"Senha do painel não configurada no Render."},503);if(!b.password||String(b.password)!==expected)return json(res,{ok:false,error:"Senha inválida."},401);const s=crypto.randomBytes(32).toString("hex");sessions.add(s);return json(res,{ok:true},200,{"Set-Cookie":`sd_staff=${s}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`})});if(url.pathname==="/api/staff/logout"&&req.method==="POST"){sessions.delete(getCookie(req,"sd_staff"));return json(res,{ok:true})}if(!staff(req,res))return;if(url.pathname==="/api/staff/wl"&&req.method==="GET")return json(res,{ok:true,items:await listW(url.searchParams.get("status"))});const m=url.pathname.match(/^\/api\/staff\/wl\/([^/]+)$/);if(!m)return json(res,{ok:false,error:"Rota não encontrada."},404);const protocol=decodeURIComponent(m[1]);if(req.method==="GET"){const item=await getW(protocol);return item?json(res,{ok:true,item}):json(res,{ok:false,error:"WL não encontrada."},404)}if(req.method==="POST")return readBody(req).then(async b=>{const old=await getW(protocol),status=b.status;if(!old)return json(res,{ok:false,error:"WL não encontrada."},404);if(old.status!=="Em análise")return json(res,{ok:false,error:`Esta WL já está ${old.status}.`},409);if(!["Aprovada","Reprovada"].includes(status))return json(res,{ok:false,error:"Status inválido."},400);const guildId=await guildForWL();const item=await reviewW(protocol,status,"Painel da Staff",clean(b.reason,500));await dm(item.discord,item);if(guildId)await setMemberRoles(guildId,item.discord,status);return json(res,{ok:true,item})});return json(res,{ok:false,error:"Método não permitido."},405)}
function verify(req,raw){const s=req.headers["x-signature-ed25519"],t=req.headers["x-signature-timestamp"],k=process.env.DISCORD_PUBLIC_KEY;if(!s||!t||!k)return false;try{return nacl.sign.detached.verify(Buffer.from(t+raw),Buffer.from(s,"hex"),Buffer.from(k,"hex"))}catch{return false}}
async function interaction(req,res){if(req.method!=="POST")return json(res,{ok:false},405);let raw="";await new Promise((resolve,reject)=>{req.on("data",c=>raw+=c);req.on("end",resolve);req.on("error",reject)});if(!verify(req,raw))return json(res,{ok:false},401);let p;try{p=JSON.parse(raw)}catch{return json(res,{ok:false},400)}if(p.type===1)return json(res,{type:1});if(p.type!==3)return json(res,{type:4,data:{content:"Interação não suportada.",flags:64}});if(process.env.DISCORD_STAFF_ROLE_ID&&!p.member?.roles?.includes(process.env.DISCORD_STAFF_ROLE_ID))return json(res,{type:4,data:{content:"Você não possui permissão para analisar WLs.",flags:64}});const [pre,act,protocol]=String(p.data?.custom_id||"").split(":");if(pre!=="wl"||!protocol)return json(res,{type:4,data:{content:"Ação inválida.",flags:64}});const old=await getW(protocol);if(!old)return json(res,{type:4,data:{content:"WL não encontrada.",flags:64}});if(old.status!=="Em análise")return json(res,{type:4,data:{content:`Esta WL já está **${old.status}**.`,flags:64}});const status=act==="approve"?"Aprovada":act==="reject"?"Reprovada":null;if(!status)return json(res,{type:4,data:{content:"Ação inválida.",flags:64}});const reviewer=p.member?.user?.global_name||p.member?.user?.username||"Staff";const appId=p.application_id,token=p.token,guildId=p.guild_id;json(res,{type:6});reviewW(protocol,status,reviewer,status==="Reprovada"?"Reprovada pela Staff":"").then(async item=>{if(!item)return;await dm(item.discord,item);if(guildId)await setMemberRoles(guildId,item.discord,status);if(appId&&token)try{await webhookEdit(appId,token,{embeds:embeds(item),components:[]})}catch(e){console.error("WL INTERACTION EDIT:",e.message)}}).catch(e=>console.error("WL INTERACTION:",e.message))}
function staticFile(req,res){let p=decodeURIComponent(new URL(req.url,`http://${req.headers.host||"localhost"}`).pathname);if(p==="/")p="/index.html";const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT))return json(res,{ok:false},403);fs.stat(f,(e,s)=>{if(!e&&s.isDirectory())return file(path.join(f,"index.html"),res);file(f,res)})}
function file(f,res){fs.readFile(f,(e,d)=>{if(e){res.writeHead(404,{"Content-Type":"text/plain; charset=utf-8"});return res.end("Página não encontrada.")}res.writeHead(200,{"Content-Type":MIME[path.extname(f).toLowerCase()]||"application/octet-stream"});res.end(d)})}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers]});
client.once("ready",()=>console.log(`Discord conectado como ${client.user.tag} • cargos WL ativos`));
client.on("guildMemberAdd",async member=>{try{await setMemberRoles(member.guild.id,member.id,"join");console.log(`Cargo Não Verificado aplicado: ${member.user.tag}`)}catch(e){console.error("WL ENTRADA:",e.message)}});
if(process.env.DISCORD_BOT_TOKEN)client.login(process.env.DISCORD_BOT_TOKEN).catch(e=>console.error("DISCORD LOGIN:",e.message));else console.error("DISCORD_BOT_TOKEN não configurado");
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||"localhost"}`);try{if(u.pathname==="/api/health")return json(res,{ok:true,status:"online",database:pool?"postgresql":"memory"});if(u.pathname==="/api/wl")return wl(req,res);if(u.pathname.startsWith("/api/staff/"))return staffApi(req,res,u);if(u.pathname==="/api/discord/interactions")return interaction(req,res);return staticFile(req,res)}catch(e){console.error("SERVER",e);return json(res,{ok:false,error:"Erro interno."},500)}});
(async()=>{try{await initDb();server.listen(PORT,"0.0.0.0",()=>console.log(`Sudeste RP online na porta ${PORT} • ${pool?"PostgreSQL ativo":"banco ausente"}`))}catch(e){console.error("DATABASE:",e);process.exit(1)}})();
